### ISSUE TITLE
TypeError: Cannot read property 'subtractCow' of null

### ISSUE THREAD

**Issue by richard-to** [richard-to/too-many-cooks#31]
Seems to be caused when the cow falls into a pit.

```
Error: Uncaught [TypeError: Cannot read property 'subtractCow' of null]
    at reportException (/Projects/too-many-cooks/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at Timeout.task [as _onTimeout] (/Projects/too-many-cooks/node_modules/jsdom/lib/jsdom/browser/Window.js:521:9)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) TypeError: Cannot read property 'subtractCow' of null
    at Cow.removeEvents (/Projects/too-many-cooks/server/game/sprites/items.js:163:23)
    at GameScene.onWorldBounds (/Projects/too-many-cooks/server/game/scene.js:341:14)
    at World.emit (/Projects/too-many-cooks/node_modules/phaser/node_modules/eventemitter3/index.js:185:35)
    at Body.update (/Projects/too-many-cooks/node_modules/phaser/src/physics/arcade/Body.js:1023:28)
    at Body.preUpdate (/Projects/too-many-cooks/node_modules/phaser/src/physics/arcade/Body.js:980:18)
    at World.update (/Projects/too-many-cooks/node_modules/phaser/src/physics/arcade/World.js:954:22)
    at EventEmitter.emit (/Projects/too-many-cooks/node_modules/phaser/node_modules/eventemitter3/index.js:203:33)
    at Systems.step (/Projects/too-many-cooks/node_modules/phaser/src/scene/Systems.js:379:21)
    at SceneManager.update (/Projects/too-many-cooks/node_modules/phaser/src/scene/SceneManager.js:565:21)
    at PhaserGame.headlessStep (/Projects/too-many-cooks/node_modules/phaser/src/core/Game.js:537:20)
```

**Comment by richard-to** [comment]
Fixed. Issue was that the one of the delete sprite calls was only removing the sprite from the scene but not fully deleting it.
